anchor_version = "0.22.1"
solana_version = "1.9.12"

[workspace]
members = [
    "fuzz",
    "stable-swap-anchor",
    "stable-swap-client",
    "stable-swap-math",
    "stable-swap-math/sim",
    "stable-swap-program/program"
]

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.mainnet]
stable_swap = "SSwpkEEcbUqx4vtoEByFjSkhKdCT862DNVb52nZg1UZ"

[programs.devnet]
stable_swap = "SSwpkEEcbUqx4vtoEByFjSkhKdCT862DNVb52nZg1UZ"

[programs.testnet]
stable_swap = "SSwpkEEcbUqx4vtoEByFjSkhKdCT862DNVb52nZg1UZ"

[programs.localnet]
stable_swap = "SSwpkEEcbUqx4vtoEByFjSkhKdCT862DNVb52nZg1UZ"
