[package]
name = "stable-swap-anchor"
version = "1.0.0"
description = "Anchor bindings for the StableSwap Rust client."
license = "Apache-2.0"
authors = ["michaelhly <michaelhly@gmail.com>"]
edition = "2018"

[dependencies]
anchor-lang = "0.13.2"
anchor-spl = "0.13.2"
stable-swap-client = { path = "../stable-swap-client", version = "1.0.0" }
