[package]
name = "stable-swap-client"
version = "1.0.0"
description = "StableSwap Rust client."
license = "Apache-2.0"
authors = ["michaelhly <michaelhly@gmail.com>"]
edition = "2018"

[dependencies]
anchor-lang = "0.13.1"
anchor-spl = "0.13.1"
arbitrary = { version = "1.0.2", features = ["derive"], optional = true }
arrayref = "0.3.6"
num-derive = "0.3"
num-traits = "0.2"
solana-program = "1.7.8"
spl-token = { version = "3.1.1", features = ["no-entrypoint"] }
thiserror = "1.0"
